import React, { useState } from 'react';
import { 
  X, 
  Download, 
  Copy, 
  Check, 
  FileText, 
  FileCode, 
  Share2,
  CheckCircle2 
} from 'lucide-react';
import { AnalysisResult } from '../types';

interface ExportDossierModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: AnalysisResult;
}

export const ExportDossierModal: React.FC<ExportDossierModalProps> = ({
  isOpen,
  onClose,
  result
}) => {
  const [tab, setTab] = useState<'markdown' | 'flowchart_only' | 'json'>('markdown');
  const [copied, setCopied] = useState<boolean>(false);

  if (!isOpen) return null;

  const markdownContent = `# CS Research Analysis Dossier: ${result.paper.title}

> **Authors:** ${result.paper.authors?.join(', ') || 'N/A'}  
> **Domain / Category:** ${result.paper.venueOrCategory || result.paper.primaryDomain || 'Computer Science'} (${result.paper.year || 'N/A'})  
> **Source URL:** ${result.paper.url || 'N/A'}  
> **Operational Token Efficiency:** ${result.tokenEfficiencyStats?.estimatedTokensIngested || '~1,900'} / 25,000 tokens

---

## 1. CORE CONCEPT EXTRACTION (<300 words)

### Problem Statement
${result.coreConcept.problemStatement}

### Primary Methodology
${result.coreConcept.primaryMethodology}

### Mathematical & Algorithmic Breakthroughs
${result.coreConcept.mathematicalAlgorithmicBreakthroughs}

### Accessible Undergrad Synthesis
${result.coreConcept.plainLanguageSummary}

---

## 2. ARCHITECTURAL FLOWCHART (Mermaid.js)

[FLOWCHART]
${result.mermaidFlowchart}

---

## 3. FUTURE WORK & INTERNSHIP OPPORTUNITIES (3rd-Year CS Student Resume Projects)

${result.futureWorkOpportunities.map((opp, idx) => `
### Project #${opp.id || idx + 1}: ${opp.projectTitle}
- **The Exact Extension:** ${opp.exactExtension}
- **Targeted Performance Metric:** ${opp.targetedPerformanceMetric}
- **Recommended Tech Stack:** ${opp.recommendedTechStack.join(', ')}
- **Difficulty Level:** ${opp.difficultyLevel} (Estimated: ${opp.estimatedWeeks})
- **Ready-To-Paste Resume Bullet:**
  - *"${opp.resumeBullet}"*
- **Base Repo to Fork:** ${opp.starterGithubIdea || 'HuggingFace / PyTorch GitHub'}
- **Milestones:**
${opp.milestones?.map(m => `  1. ${m}`).join('\n') || '  1. Phase 1: Setup and baseline\n  2. Phase 2: Implementation\n  3. Phase 3: Benchmarking'}
`).join('\n')}

---
*Generated by PaperArchitect - Advanced CS Research Agent*
`;

  const flowchartOnly = `[FLOWCHART]\n${result.mermaidFlowchart}`;
  const jsonContent = JSON.stringify(result, null, 2);

  const getActiveText = () => {
    if (tab === 'markdown') return markdownContent;
    if (tab === 'flowchart_only') return flowchartOnly;
    return jsonContent;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getActiveText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const ext = tab === 'json' ? 'json' : 'md';
    const blob = new Blob([getActiveText()], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${result.paper.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_dossier.${ext}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-md flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-3xl max-h-[85vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Modal Header */}
        <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between bg-slate-950/80">
          <div className="flex items-center gap-2">
            <Share2 className="w-5 h-5 text-cyan-400" />
            <h3 className="text-sm font-semibold text-slate-100">
              Export Research Agent Dossier
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-200 hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Selection */}
        <div className="px-6 py-2.5 bg-slate-950/40 border-b border-slate-800 flex items-center justify-between gap-3">
          <div className="flex items-center gap-1.5">
            <button
              onClick={() => setTab('markdown')}
              className={`px-3 py-1 rounded-lg text-xs font-medium transition-colors ${
                tab === 'markdown' 
                  ? 'bg-cyan-600 text-white' 
                  : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'
              }`}
            >
              Full Markdown Dossier (.md)
            </button>
            <button
              onClick={() => setTab('flowchart_only')}
              className={`px-3 py-1 rounded-lg text-xs font-medium transition-colors ${
                tab === 'flowchart_only' 
                  ? 'bg-cyan-600 text-white' 
                  : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'
              }`}
            >
              Raw [FLOWCHART] Only
            </button>
            <button
              onClick={() => setTab('json')}
              className={`px-3 py-1 rounded-lg text-xs font-medium transition-colors ${
                tab === 'json' 
                  ? 'bg-cyan-600 text-white' 
                  : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'
              }`}
            >
              JSON Data (.json)
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium rounded-lg border border-slate-700 transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-3 py-1 bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-medium rounded-lg transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download</span>
            </button>
          </div>
        </div>

        {/* Text Area Content */}
        <div className="flex-1 p-6 overflow-hidden flex flex-col bg-slate-950">
          <textarea
            readOnly
            value={getActiveText()}
            className="flex-1 w-full bg-slate-900 border border-slate-800 rounded-xl p-4 text-xs font-mono text-slate-300 resize-none focus:outline-none overflow-y-auto leading-relaxed"
          />
        </div>

        {/* Modal Footer */}
        <div className="px-6 py-3 border-t border-slate-800 bg-slate-950/80 flex items-center justify-between text-xs text-slate-500">
          <span>Formatted according to system prompt specifications</span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs font-medium transition-colors"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
};
